"""Sync model with database schema

Revision ID: 57d75c1701c5
Revises: 20260522_000002
Create Date: 2026-05-24 13:15:29.284689
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '57d75c1701c5'
down_revision = '20260522_000002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_index('ix_jobs_next_retry_at', table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_column('jobs', 'last_heartbeat_at')
    op.drop_column('jobs', 'locked_by')
    op.drop_column('jobs', 'request_id')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'created_by')
    op.drop_column('jobs', 'cancelled_at')
    op.drop_column('jobs', 'lock_expires_at')
    op.drop_column('jobs', 'queued_at')
    op.drop_column('jobs', 'failed_at')
    op.drop_column('jobs', 'current_step')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'progress_percent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('progress_percent', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('jobs', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('current_step', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('failed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('lock_expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('cancelled_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('request_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('locked_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('jobs', sa.Column('last_heartbeat_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index('ix_jobs_next_retry_at', 'jobs', ['next_retry_at'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_table('prediction_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('smiles', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('dataset', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('top_k', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('return_sequence', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), autoincrement=False, nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='prediction_jobs_pkey')
    )
    # ### end Alembic commands ###
