"""Add columns that support retry-backoff mechanism

Revision ID: 73e51f1297da
Revises: 57d75c1701c5
Create Date: 2026-05-26 13:46:36.101814
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73e51f1297da'
down_revision = '57d75c1701c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('locked_by', sa.String(length=100), nullable=True))
    op.add_column('jobs', sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('jobs', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'failed_at')
    op.drop_column('jobs', 'completed_at')
    op.drop_column('jobs', 'started_at')
    op.drop_column('jobs', 'locked_at')
    op.drop_column('jobs', 'locked_by')
    # ### end Alembic commands ###
